version: '2'

services:
  web:
    build: .
    expose:
      - 8000
    command: gunicorn kurokumo.wsgi -b 0.0.0.0:8000 --reload
    volumes:
      - .:/var/www
    links:
      - memcached
    env_file: .env
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/:/etc/nginx/
    volumes_from:
      - web
    links:
      - web
    restart: always

  memcached:
    image: memcached
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - nginx
    environment:
      STAGE: production
      DOMAINS: 'kumo.lightnet328.com -> http://nginx'
    restart: always
